stages:
  # Stage 1: Data ingestion
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  # Stage 2: Data preprocessing
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/interim


  # Stage 3: Feature engineering
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/interim
    - src/feature_engineering.py
    outs:
    - data/processed

  # Stage 4: Model building
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/processed
    - src/model_building.py
    params:
    - models.knn
    - models.svc
    - models.logistic_regression
    - models.random_forest
    - models.decision_tree
    outs:
    - models/

  # Stage 5: Model evaluation
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/
    - src/model_evaluation.py
    params:
    - evaluation.mlflow_experiment
    - evaluation.metrics_output
    metrics:
    - reports/metrics.json



# Global experiment tracking
params:
- params.yaml
metrics:
- reports/metrics.json
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
