data_ingestion:
  test_size: 0.25

data:
  train_path: "./data/processed/train_scaled.csv"
  test_path: "./data/processed/test_scaled.csv"

models:
  knn:
    n_neighbors: [3, 5, 7, 9, 11, 15]
    p: [1, 2]

  svc:
    kernel: ["rbf", "linear", "poly", "sigmoid"]

  logistic_regression: {}

  random_forest:
    n_estimators: [100, 200]
    criterion: ["gini", "entropy"]
    min_samples_split: [2, 4, 6, 8]
    min_samples_leaf: [1, 2, 3, 4, 5, 6, 7, 8]

  decision_tree:
    criterion: ["gini", "entropy"]
    min_samples_split: [2, 4, 6, 8]
    min_samples_leaf: [1, 2, 3, 4, 5, 6, 7, 8]

files:
  - "models/knn_best_model.pkl"
  - "models/svc_best_model.pkl"
  - "models/logistic_regression_best_model.pkl"
  - "models/random_forest_best_model.pkl"
  - "models/decision_tree_best_model.pkl"

evaluation:
  mlflow_experiment: "Customer_Churn_Model_Evaluation_v2"
  metrics_output: "reports/metrics.json"
